export { MetadataService } from './services/metadata'
export { RelatedService } from './services/related'
export { BookReaderJsIaService } from './services/bookreader-jsia'
export { Item } from './controllers/item/item'
export { BookController } from './controllers/book/book'