name: App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: Install dependencies
      working-directory: packages/icons
      run: npm install

    - name: Run tests
      working-directory: packages/icons
      run: npx eslint
