name: Icons CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: 19.x

    - name: Install dependencies
      working-directory: ui/icon
      run: npm install

    - name: Run tests
      working-directory: ui/icon
      run: npx eslint
