# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install && npm install -g codecov
    - run: lerna bootstrap
    - run: lerna run test && codecov

# TODO: Get slack notifications working (this is from our old travis.yml)
# notifications:
#   slack:
#     secure: tmiJdp/R2JGaS5p4ukdh2KhOo0XNV1+Wcpoz9O0dimYYeDefS6YGNzyjqzCXPM7Vb7kb48OCieoeUsrGuVlpRVLISp7Pk4z8Md2qQFYPZRQh+TBeLyIQXD2c1NOHt3qXrP9z2GNZZD/S4LXS1vsVfdVXEh7XMeujvFJm82zfuCREm12l8W4qUK7cXyDA92S3P0n/JIfL2/G6644EitdNVRSvUy8ZJXJJBalwfbRfeatJThEFDfgHSdm0kqbKhea0UN4R7WcMY02M2YVmdYNW2/GXEaX5nTc3jePjExWzXBnqrPDK2WRDhbSpvaouLaXnF8DyYAusVpMvuALpaXXVhabIcOQFYCFeFoWhdoMOhkVrBhB3s0qxiQyu5ZdBRjjGjtvyBvLwHZApXBeuCNGmBYTh+DlB5co4K5IVmE9JVOII52D11EpH+M/ZDlnYBKlUjZfkQXitxxITJXd4LAbTABnB1lBr4PUsPX8+I25w6GpAR31CkPH7dG7I6EPYKXDI+k6TjE/euSKdsu+drzduW+yfKm0SQCzRSCm4zBx1v0haTXXuqPr66m4ZleyLd9qoiGSzuM0WQpR3uB/EyFQm6qYLcHKISn0rQTRywWOh9c/LtjMXaheadMUanA35JWCZ2AtcpBOwPCeq9YpiiYv4dTr7l8R4oP3ogYzfW6TUI/c=
#     exclude:
#       if: (fork = true)
